#ifndef CARAPACE_FFI_H
#define CARAPACE_FFI_H

#pragma once

/* Generated by cbindgen. Do not edit by hand. Regenerate: cargo test -p carapace-ffi --test header regenerate_header -- --ignored --exact */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <IOSurface/IOSurfaceRef.h>

/**
 * ABI major version. Bumped on breaking changes; a host compares this against its own header at
 * load time. See `carapace_abi_version`.
 */
#define CARAPACE_ABI_MAJOR 3

/**
 * ABI minor version. Bumped on additive (backward-compatible) changes.
 */
#define CARAPACE_ABI_MINOR 1

/**
 * Result of every fallible export. Additive: append new variants, never reorder.
 */
enum CarapaceStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Success.
   */
  Ok = 0,
  /**
   * A required pointer argument was null.
   */
  ErrNullArg = 1,
  /**
   * The skin path was missing, unreadable, or failed to load/parse.
   */
  ErrBadSkin = 2,
  /**
   * GPU/adapter initialization failed.
   */
  ErrGpuInit = 3,
  /**
   * The handle's render thread has panicked and poisoned the handle; every subsequent command
   * export short-circuits with this until the handle is destroyed.
   */
  ErrPoisoned = 4,
  /**
   * A panic was caught during this call (e.g. inside `carapace_create` or `carapace_hit_test`)
   * without poisoning the handle.
   */
  ErrPanic = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum CarapaceStatus CarapaceStatus;
#else
typedef int32_t CarapaceStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Pointer event kind, mirrored 1:1 by the Rust `queue::PointerKind` the render thread consumes.
 */
enum CarapacePointerKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * A pointer press (button/touch down). The only variant the engine currently models.
   */
  Press = 0,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * A pointer release (button/touch up). Plumbed through as a forward-compatible no-op today.
   */
  Release = 1,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * A pointer move. Plumbed through as a forward-compatible no-op today.
   */
  Move = 2,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * A pointer entering the surface. Plumbed through as a forward-compatible no-op today.
   */
  Enter = 3,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * A pointer leaving the surface. Plumbed through as a forward-compatible no-op today.
   */
  Leave = 4,
#endif
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum CarapacePointerKind CarapacePointerKind;
#else
typedef int32_t CarapacePointerKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * The present path the engine resolved to. Mirrors `render::Tier`.
 */
enum CarapaceTier
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * CPU round-trip fallback: frames are read back from the GPU and copied into the IOSurface.
   */
  Readback = 1,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * Zero-copy GPU path: a Metal texture aliases the IOSurface directly.
   */
  Shared = 2,
#endif
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum CarapaceTier CarapaceTier;
#else
typedef int32_t CarapaceTier;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Classification of a point for a host embedder. Additive enum.
 */
enum CarapaceHitKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * Event should fall through the skin (transparent / passthrough region).
   */
  Passthrough = 0,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * Skin consumes the event (a control, or opaque non-interactive skin).
   */
  Control = 1,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * Host should move the window (a drag region).
   */
  Drag = 2,
#endif
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum CarapaceHitKind CarapaceHitKind;
#else
typedef int32_t CarapaceHitKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Opaque handle handed across the C ABI — a thread-safe front-end for the render thread.
 *
 * `poisoned` is set (with `Release`) by the render thread / guard after a caught panic; front-end
 * query exports read it with `Acquire` and short-circuit with `ErrPoisoned`.
 */
typedef struct CarapaceEngine CarapaceEngine;
#endif

/**
 * C function table the Swift app registers. Swift IS the host.
 */
typedef struct {
  /**
   * Opaque host context, passed unchanged as the first argument to every callback below.
   */
  void *ctx;
  /**
   * Numeric state read: given a NUL-terminated key, write the value through `out` and return
   * `true` if the host has it, else return `false` and leave `out` untouched.
   */
  bool (*get_num)(void*, const char*, double*);
  /**
   * String state read: given a NUL-terminated key, the host writes a NUL-terminated string into
   * `buf` (capacity `cap`) and returns `true` if it has the key, else returns `false`.
   */
  bool (*get_str)(void*, const char*, char*, uintptr_t);
  /**
   * Perform a host action identified by a NUL-terminated action name (the C mirror of
   * `Host::invoke`).
   */
  void (*invoke)(void*, const char*);
  /**
   * v2: fired on the render thread when a frame lands in `surfaces[index]`. `frame_id` is a
   * monotonic counter starting at 1. Must be thread-safe, non-blocking, and MUST NOT call any
   * `carapace_*` function (that reenters the queue/loop and can deadlock).
   */
  void (*frame_ready)(void*, uint32_t, uint64_t);
  /**
   * v3: number of rows in `collection` (NUL-terminated). Null = no collections.
   */
  uint32_t (*row_count)(void*, const char*);
  /**
   * v3: write row `index`'s string `field` into `buf` (cap `cap`), NUL-terminated; return
   * `true` if present. Tried after `get_row_num` (mirrors `get`, which reads numeric first).
   */
  bool (*get_row_str)(void*, const char*, uint32_t, const char*, char*, uintptr_t);
  /**
   * v3: write row `index`'s numeric `field` through `out`; return `true` if present.
   */
  bool (*get_row_num)(void*, const char*, uint32_t, const char*, double*);
  /**
   * v3: perform a host action carrying a single numeric argument (the C mirror of
   * `Host::invoke` with one `Value::Num`, e.g. `seek`, `set_volume`, `play_index`).
   */
  void (*invoke_arg)(void*, const char*, double);
} CarapaceHostVTable;

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Parameters for `carapace_create`. Grouped in a struct so create can grow additively.
 */
typedef struct {
  /**
   * NUL-terminated UTF-8 skin directory path (borrowed for the call).
   */
  const char *skin_dir;
  /**
   * Host callbacks (fn pointers must outlive the engine).
   */
  CarapaceHostVTable vtable;
  /**
   * Pointer to a caller-owned array of `surface_count` BGRA IOSurfaces, each of size `w`x`h`,
   * that outlive the engine. The render thread rotates through this pool.
   */
  const IOSurfaceRef *surfaces;
  /**
   * Number of surfaces in `surfaces`; must be >= 1.
   */
  uint32_t surface_count;
  /**
   * Optional live host content for a `view{ id = "host" }` cutout; null = none.
   */
  IOSurfaceRef content_surface;
  /**
   * Surface pixel width; must match every surface in `surfaces` (and `content_surface`, if set).
   */
  uint32_t w;
  /**
   * Surface pixel height; must match every surface in `surfaces` (and `content_surface`, if set).
   */
  uint32_t h;
} CarapaceCreateDesc;
#endif

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The ABI version this library implements: `MAJOR << 16 | MINOR`. Additive changes bump MINOR;
 * breaking changes bump MAJOR. A host compares this against the header's constants at load time.
 */
uint32_t carapace_abi_version(void);

/**
 * Copy the current thread's last error into `buf` (NUL-terminated, truncated to `cap`). Returns
 * the number of bytes the message needs (excluding NUL), so a caller can size a retry buffer.
 * Passing a null `buf` or `cap == 0` just returns that length.
 *
 * # Safety
 * `buf` must be null or point to at least `cap` writable bytes.
 */
uintptr_t carapace_last_error(char *buf, uintptr_t cap);

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Create an engine. Returns a status; on `Ok`, `*out` receives the handle (else stays null).
 *
 * Spawns a dedicated render thread that constructs and owns the engine + GPU, then BLOCKS on the
 * thread's init handshake so this call still reports `ErrBadSkin`/`ErrGpuInit`/`Ok` synchronously.
 *
 * # Safety
 * `desc` must be a valid pointer; its `skin_dir` a valid NUL-terminated UTF-8 path; `surfaces` a
 * valid array of `surface_count` live `w`x`h` BGRA IOSurfaces outliving the engine; `vtable` fn
 * pointers outliving the engine. `out` must be a valid pointer to a `*mut CarapaceEngine`.
 */
CarapaceStatus carapace_create(const CarapaceCreateDesc *desc, CarapaceEngine **out);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Destroy an engine created by `carapace_create`. Null-safe; valid on a poisoned/exited handle.
 * Signals the render thread to shut down and joins it.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not be used afterward.
 */
void carapace_destroy(CarapaceEngine *ptr);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Request a single frame be rendered now (wakes a paused engine; on a running engine it simply
 * renders ahead of the next free-run interval). Non-blocking — enqueues the request and returns
 * immediately; the render thread renders it the next time it drains the queue. Under full surface
 * backpressure (the host is holding every pooled surface) the requested frame may be skipped until
 * the host releases one (best-effort; see `carapace_release_surface`).
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not have been passed to `carapace_destroy`.
 */
CarapaceStatus carapace_invalidate(CarapaceEngine *ptr);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Set the free-run target frame rate; `0` pauses the render thread (it then only renders on
 * `carapace_invalidate`/pointer events). Default is 60. Non-blocking — enqueues the request and
 * returns immediately; the render thread picks up the new rate the next time it drains the queue.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not have been passed to `carapace_destroy`.
 */
CarapaceStatus carapace_set_frame_rate(CarapaceEngine *ptr, uint32_t fps);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Tell the render thread the host is done displaying `surfaces[index]`; it may be rendered into
 * again.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not have been passed to `carapace_destroy`.
 */
CarapaceStatus carapace_release_surface(CarapaceEngine *ptr, uint32_t index);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Swap the running skin to the one at `skin_dir`, keeping the host, GPU, and render thread.
 * Synchronous: blocks until the render thread has loaded + applied the new skin (~<=1 frame), so
 * a bad skin dir is reported as `ErrBadSkin` on the caller's thread. On failure the current skin is
 * kept. The IOSurface pool and window are unchanged — author skins to a shared design canvas.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not have been passed to `carapace_destroy`;
 * `skin_dir` must be a valid NUL-terminated UTF-8 path.
 */
CarapaceStatus carapace_swap_skin(CarapaceEngine *ptr, const char *skin_dir);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Forward a pointer event, in DESIGN-CANVAS coordinates, to the render thread. Non-blocking: this
 * enqueues `Command::Pointer` and returns immediately — the render thread applies it (and renders a
 * frame) the next time it drains the queue. Thin enough it doesn't need a panic guard of its own;
 * any panic it could cause happens later, on the render thread, inside `render_guarded`.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not have been passed to `carapace_destroy`.
 */
CarapaceStatus carapace_pointer(CarapaceEngine *ptr,
                                double x,
                                double y,
                                CarapacePointerKind kind);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Report the present tier the engine is currently using, read from the render thread's published
 * snapshot (seeded at create time via `publish_tier_only`, so this is a valid answer immediately
 * after `carapace_create` returns and after every subsequent frame). Panic-free (a lock read + a
 * match), so no panic guard is needed.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not have been passed to `carapace_destroy`. `out`
 * must be a valid pointer to a `CarapaceTier`.
 */
CarapaceStatus carapace_active_tier(CarapaceEngine *ptr, CarapaceTier *out);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Classify a point `(x, y)` in skin-local coordinates against the latest published scene. Runs on
 * the CALLER's thread (not the render thread), so it is guarded by its own `catch_unwind` at this
 * boundary rather than relying on the render thread's poison contract: on a caught panic this
 * returns `ErrPanic` (with a message retrievable via `carapace_last_error` on the caller's thread)
 * and leaves the handle usable — the render thread and its published snapshot are untouched, so
 * there is nothing to poison.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not have been passed to `carapace_destroy`. `out`
 * must be a valid pointer to a `CarapaceHitKind`.
 */
CarapaceStatus carapace_hit_test(CarapaceEngine *ptr, double x, double y, CarapaceHitKind *out);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CARAPACE_FFI_H */
