#ifndef CARAPACE_FFI_H
#define CARAPACE_FFI_H

#pragma once

/* Generated by cbindgen. Do not edit by hand. Regenerate: cargo test -p carapace-ffi --test header regenerate_header -- --ignored --exact */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define CARAPACE_ABI_MAJOR 0

#define CARAPACE_ABI_MINOR 1

/**
 * Result of every fallible export. Additive: append new variants, never reorder.
 */
enum CarapaceStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  Ok = 0,
  ErrNullArg = 1,
  ErrBadSkin = 2,
  ErrGpuInit = 3,
  ErrPoisoned = 4,
  ErrPanic = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum CarapaceStatus CarapaceStatus;
#else
typedef int32_t CarapaceStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * The present path the engine resolved to. Mirrors `render::Tier`.
 */
enum CarapaceTier
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  Readback = 1,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  Shared = 2,
#endif
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum CarapaceTier CarapaceTier;
#else
typedef int32_t CarapaceTier;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Pointer event kinds. v1 forwards all; the engine currently acts on `Press`, the rest are
 * plumbed for hover/drag semantics and forward-compat (additive).
 */
enum CarapacePointerKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  Press = 0,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  Release = 1,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  Move = 2,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  Enter = 3,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  Leave = 4,
#endif
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum CarapacePointerKind CarapacePointerKind;
#else
typedef int32_t CarapacePointerKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Classification of a point for a host embedder. Additive enum.
 */
enum CarapaceHitKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * Event should fall through the skin (transparent / passthrough region).
   */
  Passthrough = 0,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * Skin consumes the event (a control, or opaque non-interactive skin).
   */
  Control = 1,
#endif
#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
  /**
   * Host should move the window (a drag region).
   */
  Drag = 2,
#endif
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum CarapaceHitKind CarapaceHitKind;
#else
typedef int32_t CarapaceHitKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Opaque handle handed across the C ABI. `poisoned` is set by `ffi_guard!` after a caught panic;
 * every subsequent call short-circuits with `ErrPoisoned`.
 */
typedef struct CarapaceEngine CarapaceEngine;
#endif

#if ((defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)) && (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)))
typedef void *IOSurfaceRef;
#endif

/**
 * C function table the Swift app registers. Swift IS the host.
 */
typedef struct {
  void *ctx;
  bool (*get_num)(void*, const char*, double*);
  bool (*get_str)(void*, const char*, char*, uintptr_t);
  void (*invoke)(void*, const char*);
} CarapaceHostVTable;

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Parameters for `carapace_create`. Grouped in a struct so create can grow additively.
 */
typedef struct {
  /**
   * NUL-terminated UTF-8 skin directory path (borrowed for the call).
   */
  const char *skin_dir;
  /**
   * Host callbacks (fn pointers must outlive the engine).
   */
  CarapaceHostVTable vtable;
  /**
   * Caller-owned BGRA IOSurface of size `w`x`h` that outlives the engine.
   */
  IOSurfaceRef surface;
  /**
   * Optional live host content for a `view{ id = "host" }` cutout; null = none.
   */
  IOSurfaceRef content_surface;
  uint32_t w;
  uint32_t h;
} CarapaceCreateDesc;
#endif

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The ABI version this library implements: `MAJOR << 16 | MINOR`. Additive changes bump MINOR;
 * breaking changes bump MAJOR. A host compares this against the header's constants at load time.
 */
uint32_t carapace_abi_version(void);

/**
 * Copy the current thread's last error into `buf` (NUL-terminated, truncated to `cap`). Returns
 * the number of bytes the message needs (excluding NUL), so a caller can size a retry buffer.
 * Passing a null `buf` or `cap == 0` just returns that length.
 *
 * # Safety
 * `buf` must be null or point to at least `cap` writable bytes.
 */
uintptr_t carapace_last_error(char *buf, uintptr_t cap);

#if ((defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)) && (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)))
extern int32_t IOSurfaceLock(IOSurfaceRef buffer,
                             uint32_t options,
                             uint32_t *seed);
#endif

#if ((defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)) && (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)))
extern int32_t IOSurfaceUnlock(IOSurfaceRef buffer,
                               uint32_t options,
                               uint32_t *seed);
#endif

#if ((defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)) && (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)))
extern void *IOSurfaceGetBaseAddress(IOSurfaceRef buffer);
#endif

#if ((defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)) && (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)))
extern uintptr_t IOSurfaceGetBytesPerRow(IOSurfaceRef buffer);
#endif

#if ((defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)) && (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)))
extern uintptr_t IOSurfaceGetWidth(IOSurfaceRef buffer);
#endif

#if ((defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)) && (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE)))
extern uintptr_t IOSurfaceGetHeight(IOSurfaceRef buffer);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Create an engine. Returns a status; on `Ok`, `*out` receives the handle (else stays null).
 *
 * # Safety
 * `desc` must be a valid pointer; its `skin_dir` a valid NUL-terminated UTF-8 path; `surface` a
 * live `w`x`h` BGRA IOSurface outliving the engine; `vtable` fn pointers outliving the engine.
 * `out` must be a valid pointer to a `*mut CarapaceEngine`.
 */
CarapaceStatus carapace_create(const CarapaceCreateDesc *desc, CarapaceEngine **out);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Destroy an engine created by `carapace_create`. Null-safe; valid on a poisoned handle.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not be used afterward.
 */
void carapace_destroy(CarapaceEngine *ptr);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Tick + render one frame into the engine's surface. `dt_seconds` is host wall-clock time.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not be destroyed.
 */
CarapaceStatus carapace_tick(CarapaceEngine *ptr, double dt_seconds);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Report the active present tier.
 *
 * # Safety
 * `ptr` must come from `carapace_create`; `out` must be a valid pointer to a `CarapaceTier`.
 */
CarapaceStatus carapace_active_tier(CarapaceEngine *ptr, CarapaceTier *out);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Forward a pointer event in DESIGN-CANVAS coordinates.
 *
 * # Safety
 * `ptr` must come from `carapace_create`.
 */
CarapaceStatus carapace_pointer(CarapaceEngine *ptr, double x, double y, CarapacePointerKind kind);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Classify the point `(x, y)` (DESIGN-CANVAS coords) without side effects. Writes `*out`.
 *
 * # Safety
 * `ptr` must come from `carapace_create`; `out` must be non-null.
 */
CarapaceStatus carapace_hit_test(CarapaceEngine *ptr, double x, double y, CarapaceHitKind *out);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CARAPACE_FFI_H */
