#ifndef CARAPACE_FFI_H
#define CARAPACE_FFI_H

#pragma once

/* Generated by cbindgen. Do not edit by hand. Regenerate: cargo test -p carapace-ffi --test header regenerate_header -- --ignored --exact */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <IOSurface/IOSurfaceRef.h>

#define CARAPACE_ABI_MAJOR 0

#define CARAPACE_ABI_MINOR 1

/**
 * Result of every fallible export. Additive: append new variants, never reorder.
 */
enum CarapaceStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  Ok = 0,
  ErrNullArg = 1,
  ErrBadSkin = 2,
  ErrGpuInit = 3,
  ErrPoisoned = 4,
  ErrPanic = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum CarapaceStatus CarapaceStatus;
#else
typedef int32_t CarapaceStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Opaque handle handed across the C ABI — a thread-safe front-end for the render thread.
 *
 * `poisoned` is set (with `Release`) by the render thread / guard after a caught panic; front-end
 * query exports read it with `Acquire` and short-circuit with `ErrPoisoned`.
 */
typedef struct CarapaceEngine CarapaceEngine;
#endif

/**
 * C function table the Swift app registers. Swift IS the host.
 */
typedef struct {
  void *ctx;
  bool (*get_num)(void*, const char*, double*);
  bool (*get_str)(void*, const char*, char*, uintptr_t);
  void (*invoke)(void*, const char*);
  /**
   * v2: fired on the render thread when a frame lands in `surfaces[index]`. `frame_id` is a
   * monotonic counter starting at 1. Must be thread-safe, non-blocking, and MUST NOT call any
   * `carapace_*` function (that reenters the queue/loop and can deadlock).
   */
  void (*frame_ready)(void*, uint32_t, uint64_t);
} CarapaceHostVTable;

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Parameters for `carapace_create`. Grouped in a struct so create can grow additively.
 */
typedef struct {
  /**
   * NUL-terminated UTF-8 skin directory path (borrowed for the call).
   */
  const char *skin_dir;
  /**
   * Host callbacks (fn pointers must outlive the engine).
   */
  CarapaceHostVTable vtable;
  /**
   * Pointer to a caller-owned array of `surface_count` BGRA IOSurfaces, each of size `w`x`h`,
   * that outlive the engine. The render thread rotates through this pool.
   */
  const IOSurfaceRef *surfaces;
  /**
   * Number of surfaces in `surfaces`; must be >= 1.
   */
  uint32_t surface_count;
  /**
   * Optional live host content for a `view{ id = "host" }` cutout; null = none.
   */
  IOSurfaceRef content_surface;
  uint32_t w;
  uint32_t h;
} CarapaceCreateDesc;
#endif

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The ABI version this library implements: `MAJOR << 16 | MINOR`. Additive changes bump MINOR;
 * breaking changes bump MAJOR. A host compares this against the header's constants at load time.
 */
uint32_t carapace_abi_version(void);

/**
 * Copy the current thread's last error into `buf` (NUL-terminated, truncated to `cap`). Returns
 * the number of bytes the message needs (excluding NUL), so a caller can size a retry buffer.
 * Passing a null `buf` or `cap == 0` just returns that length.
 *
 * # Safety
 * `buf` must be null or point to at least `cap` writable bytes.
 */
uintptr_t carapace_last_error(char *buf, uintptr_t cap);

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Create an engine. Returns a status; on `Ok`, `*out` receives the handle (else stays null).
 *
 * Spawns a dedicated render thread that constructs and owns the engine + GPU, then BLOCKS on the
 * thread's init handshake so this call still reports `ErrBadSkin`/`ErrGpuInit`/`Ok` synchronously.
 *
 * # Safety
 * `desc` must be a valid pointer; its `skin_dir` a valid NUL-terminated UTF-8 path; `surfaces` a
 * valid array of `surface_count` live `w`x`h` BGRA IOSurfaces outliving the engine; `vtable` fn
 * pointers outliving the engine. `out` must be a valid pointer to a `*mut CarapaceEngine`.
 */
CarapaceStatus carapace_create(const CarapaceCreateDesc *desc, CarapaceEngine **out);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Destroy an engine created by `carapace_create`. Null-safe; valid on a poisoned/exited handle.
 * Signals the render thread to shut down and joins it.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not be used afterward.
 */
void carapace_destroy(CarapaceEngine *ptr);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Enqueue a render of exactly one frame now (wakes a paused engine — see `carapace_set_frame_rate`).
 * Real pacing (free-run at `fps`, coalescing) lands in Task 6; for now this is a thin `tx.send`.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not have been passed to `carapace_destroy`.
 */
CarapaceStatus carapace_invalidate(CarapaceEngine *ptr);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Set the free-run target frame rate; `0` pauses the render thread (it then only renders on
 * `carapace_invalidate`/pointer events). Real pacing behavior lands in Task 6; for now this is a
 * thin `tx.send`.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not have been passed to `carapace_destroy`.
 */
CarapaceStatus carapace_set_frame_rate(CarapaceEngine *ptr, uint32_t fps);
#endif

#if (defined(CARAPACE_APPLE) || defined(CARAPACE_APPLE))
/**
 * Tell the render thread the host is done displaying `surfaces[index]`; it may be rendered into
 * again.
 *
 * # Safety
 * `ptr` must come from `carapace_create` and not have been passed to `carapace_destroy`.
 */
CarapaceStatus carapace_release_surface(CarapaceEngine *ptr, uint32_t index);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CARAPACE_FFI_H */
